import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import './globals.css';
import Footer from './footer/page';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex`}
      >
        {/* 左侧导航栏 */}
        <nav className="w-36 bg-background border-r border-gray-200 dark:border-gray-700 p-4 rounded-r-lg shadow-md border-0 fixed h-full z-10">
          <h2 className="text-lg font-bold mb-6 text-center text-foreground">网站导航</h2>
          <ul className="space-y-2">
            <li>
              <Link 
                href="/"
                className="block p-2 rounded hover:bg-gray-100 dark:hover:bg-gray-800 hover:translate-x-1 transition-all duration-200"
              >
                首页
              </Link>
            </li>
            <li>
              <Link 
                href="/chat"
                className="block p-2 rounded hover:bg-gray-100 dark:hover:bg-gray-800"
              >
                AI聊天
              </Link>
            </li>
            <li>
              <Link 
                href="/course-repo"
                className="block p-2 rounded hover:bg-gray-200 dark:hover:bg-gray-700"
              >
                课程仓库
              </Link>
            </li>
            <li>
              <Link 
                href="/qanything"
                className="block p-2 rounded hover:bg-gray-200 dark:hover:bg-gray-700"
              >
                QAnything
              </Link>
            </li>
          </ul>
        </nav>

        {/* 右侧内容区 */}
        <main className="flex-1 ml-36">
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
